INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Paracetamol 500mg', 'Paracetamol', '500mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Paracetamol 1000mg', 'Paracetamol', '1000mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Nurofen 200mg', 'Ibuprofen', '200mg', 'Reckitt') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Nurofen 400mg', 'Ibuprofen', '400mg', 'Reckitt') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ibuprofen 200mg', 'Ibuprofen', '200mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ibuprofen 400mg', 'Ibuprofen', '400mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Algocalmin 500mg', 'Metamizol sodic', '500mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ketoprofen 100mg', 'Ketoprofen', '100mg', 'Rompharm') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Diclofenac 50mg', 'Diclofenac sodic', '50mg', 'Novartis') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Diclofenac 100mg', 'Diclofenac sodic', '100mg', 'Novartis') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Aspirin 500mg', 'Acid acetilsalicilic', '500mg', 'Bayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Aspirin Cardio 100mg', 'Acid acetilsalicilic', '100mg', 'Bayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Tramadol 50mg', 'Tramadol', '50mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Tramadol 100mg', 'Tramadol', '100mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Amoxicilina 500mg', 'Amoxicilina', '500mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Amoxicilina 1000mg', 'Amoxicilina', '1000mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Augmentin 625mg', 'Amoxicilina/Acid clavulanic', '625mg', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Augmentin 1000mg', 'Amoxicilina/Acid clavulanic', '1000mg', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ampicilina 500mg', 'Ampicilina', '500mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Azitromicina 500mg', 'Azitromicina', '500mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Claritromicina 500mg', 'Claritromicina', '500mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ciprofloxacin 500mg', 'Ciprofloxacin', '500mg', 'Bayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ciprofloxacin 250mg', 'Ciprofloxacin', '250mg', 'Bayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Doxiciclina 100mg', 'Doxiciclina', '100mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metronidazol 400mg', 'Metronidazol', '400mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Cefuroxim 500mg', 'Cefuroxim', '500mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Cefalexin 500mg', 'Cefalexin', '500mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Eritromicina 500mg', 'Eritromicina', '500mg', 'Antibiotice SA') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Levofloxacin 500mg', 'Levofloxacin', '500mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Nitrofurantoin 100mg', 'Nitrofurantoin', '100mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metoprolol 50mg', 'Metoprolol tartrat', '50mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metoprolol 100mg', 'Metoprolol tartrat', '100mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Atenolol 50mg', 'Atenolol', '50mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Amlodipina 5mg', 'Amlodipina', '5mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Amlodipina 10mg', 'Amlodipina', '10mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ramipril 5mg', 'Ramipril', '5mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ramipril 10mg', 'Ramipril', '10mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Enalapril 10mg', 'Enalapril maleат', '10mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Enalapril 20mg', 'Enalapril maleат', '20mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Lisinopril 10mg', 'Lisinopril', '10mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Lisinopril 20mg', 'Lisinopril', '20mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Losartan 50mg', 'Losartan potasic', '50mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Losartan 100mg', 'Losartan potasic', '100mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Valsartan 80mg', 'Valsartan', '80mg', 'Novartis') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Valsartan 160mg', 'Valsartan', '160mg', 'Novartis') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Bisoprolol 5mg', 'Bisoprolol fumarat', '5mg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Bisoprolol 10mg', 'Bisoprolol fumarat', '10mg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Carvedilol 25mg', 'Carvedilol', '25mg', 'Roche') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Furosemid 40mg', 'Furosemid', '40mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Spironolactona 25mg', 'Spironolactona', '25mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Digoxin 0.25mg', 'Digoxin', '0.25mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Atorvastatina 10mg', 'Atorvastatina', '10mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Atorvastatina 20mg', 'Atorvastatina', '20mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Atorvastatina 40mg', 'Atorvastatina', '40mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Rosuvastatina 10mg', 'Rosuvastatina', '10mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Rosuvastatina 20mg', 'Rosuvastatina', '20mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Simvastatina 20mg', 'Simvastatina', '20mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Simvastatina 40mg', 'Simvastatina', '40mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metformin 500mg', 'Metformin hidrochlorid', '500mg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metformin 850mg', 'Metformin hidrochlorid', '850mg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metformin 1000mg', 'Metformin hidrochlorid', '1000mg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Glibenclamid 5mg', 'Glibenclamid', '5mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Gliclazid 80mg', 'Gliclazid', '80mg', 'Servier') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Glimepirid 2mg', 'Glimepirid', '2mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Glimepirid 4mg', 'Glimepirid', '4mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Sitagliptin 100mg', 'Sitagliptin', '100mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Empagliflozin 10mg', 'Empagliflozin', '10mg', 'Boehringer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Insulina Glargine 100UI/ml', 'Insulina glargine', '100UI/ml', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Insulina Aspart 100UI/ml', 'Insulina aspart', '100UI/ml', 'Novo Nordisk') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Salbutamol 100mcg', 'Salbutamol', '100mcg/doza', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ventolin 100mcg', 'Salbutamol', '100mcg/doza', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Salmeterol 50mcg', 'Salmeterol', '50mcg/doza', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Budesonid 200mcg', 'Budesonid', '200mcg/doza', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Fluticazona 125mcg', 'Fluticazona propionat', '125mcg/doza', 'GSK') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Montelukast 10mg', 'Montelukast sodic', '10mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Bromhexin 8mg', 'Bromhexin hidrochlorid', '8mg', 'Boehringer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('ACC 600mg', 'Acetilcisteina', '600mg', 'Sandoz') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Ambroxol 30mg', 'Ambroxol hidrochlorid', '30mg', 'Boehringer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Omeprazol 20mg', 'Omeprazol', '20mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Omeprazol 40mg', 'Omeprazol', '40mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Pantoprazol 40mg', 'Pantoprazol sodic', '40mg', 'Nycomed') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Esomeprazol 20mg', 'Esomeprazol', '20mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Metoclopramid 10mg', 'Metoclopramid', '10mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Domperidon 10mg', 'Domperidon', '10mg', 'Janssen') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Loperamid 2mg', 'Loperamid', '2mg', 'Janssen') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Smecta 3g', 'Diosmectita', '3g/plic', 'Ipsen') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Duphalac 667mg/ml', 'Lactuloza', '667mg/ml', 'Solvay') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Mezym 10000', 'Pancreatina', '10000 UI', 'Berlin-Chemie') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Diazepam 5mg', 'Diazepam', '5mg', 'Roche') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Alprazolam 0.25mg', 'Alprazolam', '0.25mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Alprazolam 0.5mg', 'Alprazolam', '0.5mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Clonazepam 0.5mg', 'Clonazepam', '0.5mg', 'Roche') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Sertralin 50mg', 'Sertralina', '50mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Sertralin 100mg', 'Sertralina', '100mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Fluoxetina 20mg', 'Fluoxetina', '20mg', 'Eli Lilly') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Escitalopram 10mg', 'Escitalopram', '10mg', 'Lundbeck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Venlafaxina 75mg', 'Venlafaxina', '75mg', 'Wyeth') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Amitriptilina 25mg', 'Amitriptilina', '25mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Carbamazepina 200mg', 'Carbamazepina', '200mg', 'Novartis') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Valproat sodic 500mg', 'Acid valproic', '500mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Levetiracetam 500mg', 'Levetiracetam', '500mg', 'UCB') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Pregabalin 75mg', 'Pregabalina', '75mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Pregabalin 150mg', 'Pregabalina', '150mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Gabapentin 300mg', 'Gabapentina', '300mg', 'Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Quetiapina 25mg', 'Quetiapina', '25mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Quetiapina 100mg', 'Quetiapina', '100mg', 'AstraZeneca') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Olanzapina 5mg', 'Olanzapina', '5mg', 'Eli Lilly') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Risperidona 2mg', 'Risperidona', '2mg', 'Janssen') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Zolpidem 10mg', 'Zolpidem tartrat', '10mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Melatonina 3mg', 'Melatonina', '3mg', 'Solgar') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Euthyrox 25mcg', 'Levotiroxina sodica', '25mcg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Euthyrox 50mcg', 'Levotiroxina sodica', '50mcg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Euthyrox 100mcg', 'Levotiroxina sodica', '100mcg', 'Merck') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Tiamazol 5mg', 'Tiamazol', '5mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Vitamina C 500mg', 'Acid ascorbic', '500mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Vitamina C 1000mg', 'Acid ascorbic', '1000mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Vitamina D3 1000UI', 'Colecalciferol', '1000UI', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Vitamina D3 4000UI', 'Colecalciferol', '4000UI', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Vitamina B12 1000mcg', 'Cianocobalamina', '1000mcg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Acid folic 5mg', 'Acid folic', '5mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Fier 80mg', 'Sulfat feros', '80mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Calciu 500mg', 'Carbonat de calciu', '500mg', 'Sandoz') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Magneziu 375mg', 'Oxid de magneziu', '375mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Zinc 15mg', 'Sulfat de zinc', '15mg', 'Zentiva') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Cetirizina 10mg', 'Cetirizina dihidroclorid', '10mg', 'UCB') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Loratadina 10mg', 'Loratadina', '10mg', 'Schering-Plough') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Desloratadina 5mg', 'Desloratadina', '5mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Fexofenadina 120mg', 'Fexofenadina', '120mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Warfarina 5mg', 'Warfarina sodica', '5mg', 'Terapia') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Enoxaparina 40mg', 'Enoxaparina sodica', '40mg', 'Sanofi') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Rivaroxaban 20mg', 'Rivaroxaban', '20mg', 'Bayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Apixaban 5mg', 'Apixaban', '5mg', 'BMS/Pfizer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Dabigatran 110mg', 'Dabigatran etexilat', '110mg', 'Boehringer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Tamsulosin 0.4mg', 'Tamsulosin hidrochlorid', '0.4mg', 'Boehringer') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Finasterid 5mg', 'Finasterid', '5mg', 'MSD') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Solifenacin 5mg', 'Solifenacin succinat', '5mg', 'Astellas') ON CONFLICT (name) DO NOTHING;
INSERT INTO medications (name, active_substance, dosage, manufacturer) VALUES ('Oxybutynin 5mg', 'Oxybutynin hidrochlorid', '5mg', 'Janssen') ON CONFLICT (name) DO NOTHING;