spring:
  application:
    name: medicare-plus
  profiles:
    active: dev
  jpa:
    open-in-view: false

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html