spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:medicare_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://medicare_user:medicareMirela@medicare-cluster.k1cloqx.mongodb.net/?appName=medicare-cluster
      database: medicare_analyses
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
